server:
  port: 8082
spring:
  application:
    name: GradeMS
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/allianz
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

