server:
  port: 8088

spring:
  application:
    name: ConfigServer
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ajay4a/config-server.git
          username: ajay4a
          password: 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
          clone-on-start: true
          default-label: master


